package com.greenario.dronemanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CropItenerary implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CropItenerary id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "CropItenerary name")
	private com.greenario.dronemanagement.CropItenerary name;

	public CropItenerary() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public com.greenario.dronemanagement.CropItenerary getName() {
		return this.name;
	}

	public void setName(com.greenario.dronemanagement.CropItenerary name) {
		this.name = name;
	}

	public CropItenerary(java.lang.Integer id,
			com.greenario.dronemanagement.CropItenerary name) {
		this.id = id;
		this.name = name;
	}

}