package com.greenario.dronemanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CropHealth implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "crophealth id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "crop name")
	private com.greenario.dronemanagement.CropHealth name;

	public CropHealth() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public com.greenario.dronemanagement.CropHealth getName() {
		return this.name;
	}

	public void setName(com.greenario.dronemanagement.CropHealth name) {
		this.name = name;
	}

	public CropHealth(java.lang.Integer id,
			com.greenario.dronemanagement.CropHealth name) {
		this.id = id;
		this.name = name;
	}

}